### ISSUE TITLE
send dunes failed 

### ISSUE THREAD

**Issue by moh5217** [sirduney/dunes-cli#10]
hi, i have successfully sent first 10 dunes to another wallet , but at the second try ,  the process failed , after many try , same fail message ( wallet balance 566 dunes )  :

node dunes.js sendDunesNoProtocol D9exgUbU2mLd219ga34iW5doeey6aBnUCq 50 DUNES•ARE•SANDY
✔ Transferring 50 utxos of DUNES•ARE•SANDY. Are you sure you want to proceed? … yes

Error executing operation: Request failed with status code 500
Retrying operation in 30000 ms...
Error executing operation: Request failed with status code 500
Max retries exceeded (0), aborting operation.
Fetching unspent outputs for page 1...
Fetching unspent outputs for page 2...
Fetching unspent outputs for page 3...
Fetching unspent outputs for page 4...
Fetching unspent outputs for page 5...
Fetching unspent outputs for page 6...
Fetching unspent outputs for page 7...
Fetching unspent outputs for page 8...
Fetching unspent outputs for page 9...
Fetching unspent outputs for page 10...
Fetching unspent outputs for page 11...
Fetching unspent outputs for page 12...
Fetching unspent outputs for page 13...
balance 1148125000
ReferenceError: Cannot access 'wallet' before initialization
    at broadcast (/home/momo/dunes-new/dunes21/dunes.js:1369:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async walletSendDunesNoProtocol (/home/momo/dunes-new/dunes21/dunes.js:746:15)
    at async Command.<anonymous> (/home/momo/dunes-new/dunes21/dunes.js:588:7)

**Comment by sirduney** [comment]
This issue should be fixed now
